In [2]:
import numpy as np

In [185]:
#compute the forces on the particles at each timestep, pos = [m]/[s] = 
def lj_force(position, n):
    F = 0
    pos = position[:,-n:] # pos is in the form (3,n)
    P = np.zeros((n,3)) # P is in the form (n,3) w/ n number of particles and 3 number of dimensions 
    for i in range(n):
        P[i,:] = pos[:,i] # P is in the form (n,3)

    rel_pos = P[:, None, :] - P[None, :, :] # with P = np.array(N_particels, 3)
    r = np.sqrt(np.sum(np.power(rel_pos, 2), axis=2)) #n x n simmetric matrix, r[i,j] is the distance between the i-th and the j-th particles
    
    # Until this point:
        # this function is 3D ready
        # in order to use the int in the e-mail I switched from the form (3,n) which we use in the code to the form (n,3),
        # so this force will probably return a n x 3 matrix, but it only takes one loop to change its shape
        #
        # rel_pos are n matrices in the form x1, y1, z1
        #                                    x2, y2, z2
        #                                    ..........
        #                                    xn, yn, zn
        #
        # where the i-th line of the first matrix gives the distance of the i-th particle from the first particle,
        # the i-th line of the second matrix gives the distance of the i-th particle from the second particle and so on
        #
        # r is a n x n simmetric matrix, where the element r[i,j] is the distance between the i-th and the j-th particle
        #
        # the thing to do from here is to write the force, possibly without using loops
        
    print('P=', P, '\n')
    print('rel_pos=', rel_pos, '\n')
    print('r=',r)
    return F


In [88]:
our = np.array([[10, 5, 3, 14], [6, 5, 13, 1], [5, 8, 6, 7]]) #array in the shape we are using
our

array([[10,  5,  3, 14],
       [ 6,  5, 13,  1],
       [ 5,  8,  6,  7]])

In [89]:
h = np.zeros((4,3)) # array in the shapa that is usable in the force function

for i in range(4):
    h[i,:] = our[:,i]
h

array([[10.,  6.,  5.],
       [ 5.,  5.,  8.],
       [ 3., 13.,  6.],
       [14.,  1.,  7.]])

In [186]:
lj_force(our,4)

P= [[10.  6.  5.]
 [ 5.  5.  8.]
 [ 3. 13.  6.]
 [14.  1.  7.]] 

rel_pos= [[[  0.   0.   0.]
  [  5.   1.  -3.]
  [  7.  -7.  -1.]
  [ -4.   5.  -2.]]

 [[ -5.  -1.   3.]
  [  0.   0.   0.]
  [  2.  -8.   2.]
  [ -9.   4.   1.]]

 [[ -7.   7.   1.]
  [ -2.   8.  -2.]
  [  0.   0.   0.]
  [-11.  12.  -1.]]

 [[  4.  -5.   2.]
  [  9.  -4.  -1.]
  [ 11. -12.   1.]
  [  0.   0.   0.]]] 

r= [[ 0.          5.91607978  9.94987437  6.70820393]
 [ 5.91607978  0.          8.48528137  9.89949494]
 [ 9.94987437  8.48528137  0.         16.30950643]
 [ 6.70820393  9.89949494 16.30950643  0.        ]]


0