In [2]:
import numpy as np

In [194]:
#compute the forces on the particles at each timestep, pos = [m]/[s] = 
def lj_force(position, n):
    F = 0
    pos = position[:,-3:] # pos is in the form (n,3)
    
    rel_pos = pos[:, None, :] - pos[None, :, :] # with P = np.array(N_particels, 3)
    r = np.sqrt(np.sum(np.power(rel_pos, 2), axis=2)) #n x n simmetric matrix, r[i,j] is the distance between the i-th and the j-th particles
    
    
    
    # Until this point:
        # this function is 3D ready
        # in order to use the int in the e-mail I switched from the form (3,n) which we use in the code to the form (n,3),
        # so this force will probably return a n x 3 matrix, but it only takes one loop to change its shape
        #
        # rel_pos are n matrices in the form x1, y1, z1
        #                                    x2, y2, z2
        #                                    ..........
        #                                    xn, yn, zn
        #
        # where the i-th line of the first matrix gives the distance of the i-th particle from the first particle,
        # the i-th line of the second matrix gives the distance of the i-th particle from the second particle and so on
        #
        # r is a n x n simmetric matrix, where the element r[i,j] is the distance between the i-th and the j-th particle
        #
        # the thing to do from here is to write the force, possibly without using loops
        
    print('rel_pos=', rel_pos, '\n')
    print('r=',r)
    return F


In [195]:
our = np.array([[0.1, 0.8, 0.3], [0.6, 0.5, 0.13]]) # n x 3 matrix with n = 2
our

array([[0.1 , 0.8 , 0.3 ],
       [0.6 , 0.5 , 0.13]])

In [196]:
lj_force(our,-2)

rel_pos= [[[ 0.    0.    0.  ]
  [-0.5   0.3   0.17]]

 [[ 0.5  -0.3  -0.17]
  [ 0.    0.    0.  ]]] 

r= [[0.         0.60737139]
 [0.60737139 0.        ]]


0