In [1]:
import numpy as np

In [2]:
e = 1.65*pow(10,-21)
s = 3.405*pow(10,-10)
def lj_force(pos):
    rel_pos=pos[0,:]-pos[1,:]
    dist = np.linalg.norm(pos[1,:]-pos[0,:])
    r = dist
    F = rel_pos*((24*e/pow(r,2))*(pow(s/r,6))*((pow(s/r,6))-1))
    return F
a = np.array([[0.1, 0.2],
        [0.3, 0.4]])
lj_force(a)

array([3.01347735e-73, 3.01347735e-73])

In [7]:
m = 1       #Argon Mass
time_step = 10**(-4)
final_matrix_pos = np.array([[0.1, 0.2],
        [0.3, 0.4]])
final_matrix_vel = np.array([[40, 100],
        [350, -40]])

In [9]:
latest_pos = final_matrix_pos[:,-2:]          
latest_vel = final_matrix_vel[:,-2:]

lj_force(latest_pos)

array([3.01347735e-73, 3.01347735e-73])

In [8]:
def euler(final_matrix_pos, final_matrix_vel):
    latest_pos = final_matrix_pos[:,-2:]          #the -2 will eventually become -(number of particles)
    latest_vel = final_matrix_vel[:,-2:]
    
    new_latest_pos = latest_pos + latest_vel * time_step
    new_latest_vel = latest_vel + 1/m * lj_force(latest_pos)
    return "position", new_latest_pos,"velocity", new_latest_vel

euler(final_matrix_pos, final_matrix_vel)

('position',
 array([[0.104, 0.21 ],
        [0.335, 0.396]]),
 'velocity',
 array([[ 40., 100.],
        [350., -40.]]))