In [2]:
import skeleton as s
import numpy as np

In [3]:
init_pos = np.random.uniform(low=0, high=1.0, size=(2, 2))
init_vel = np.random.uniform(low=-430, high=430, size=(2, 2))

In [4]:
print("pos\n", init_pos,"\n vel\n" ,init_vel)
print("y_values\n", init_pos[:, 1])
later_positions = init_pos + np.random.uniform(low=0, high=1.0, size=(2, 2))
print("later positions\n" , later_positions)
np.concatenate((init_pos, later_positions), axis=1, out=None)

pos
 [[0.72004323 0.21592059]
 [0.22136561 0.40154733]] 
 vel
 [[429.06913959 199.0120369 ]
 [109.20851122 207.42987252]]
y_values
 [0.21592059 0.40154733]
later positions
 [[1.6023643  0.66891085]
 [0.9780363  1.03414858]]


array([[0.72004323, 0.21592059, 1.6023643 , 0.66891085],
       [0.22136561, 0.40154733, 0.9780363 , 1.03414858]])

In [6]:
#Create a 2x8 matrix to store the position of each particle at each step in time.
number_of_steps = 3
pos_steps = np.copy(init_pos)
next_step_position = np.copy(init_pos)

for i in range(number_of_steps):
    next_step_position += np.random.uniform(low=0, high=1.0, size=(2, 2))
    for k in range(2): #implement boundary conditions
        for j in range(2):
            if next_step_position[k, j] > 1:
                next_step_position[k, j] -= 1
            elif next_step_position[k, j] < 0:
                next_step_position[k, j] += 1
    pos_steps =  np.concatenate((pos_steps, next_step_position), axis=1, out=None)

print(pos_steps)

[[0.72004323 0.21592059 0.03899029 0.03978598 0.15258655 0.06738025
  0.14431238 0.08280284]
 [0.22136561 0.40154733 0.05940102 0.10183335 0.78537088 0.11542433
  0.81793312 0.47422327]]


In [7]:
#Create a 2x8 matrix to store the velocity of each particle at each step in time.
vel_steps = np.copy(init_vel)
next_step_velocity = np.copy(init_vel)

for i in range(number_of_steps):
    next_step_velocity += np.random.uniform(low=-100, high=100, size=(2, 2))
    vel_steps =  np.concatenate((vel_steps, next_step_velocity), axis=1, out=None)

print(vel_steps)

[[429.06913959 199.0120369  355.28947365 146.44357877 311.26848442
  141.06992864 280.44727685 113.9931523 ]
 [109.20851122 207.42987252  25.21536702 199.49522355 -26.22014595
  287.43261335  21.25404562 252.05031906]]
