In [2]:
import skeleton as s
import numpy as np

1st column: x_coordinate, 
second column: y_coordinate;
size(number of particles, number of dimensions)

In [3]:
init_pos = np.random.uniform(low=0, high=1.0, size=(2, 2))
init_vel = np.random.uniform(low=-430, high=430, size=(2, 2))

print("pos\n", init_pos,"\n vel\n" ,init_vel)
print("y_values\n", init_pos[:, 1])

pos
 [[0.29411138 0.02089936]
 [0.99442135 0.79080608]] 
 vel
 [[ 213.8707139  -373.33513015]
 [ 423.78747688   28.65333691]]
y_values
 [0.02089936 0.79080608]


In [4]:
def function(init_pos, init_vel):
    later_positions = np.random.uniform(low=0, high=1.0, size=(2, 2))
    np.concatenate((init_pos, later_positions), axis=1, out=None)
    
function(init_pos, init_vel)

In [5]:
later_positions = init_pos + np.random.uniform(low=0, high=1.0, size=(2, 2))
print("later positions\n" , later_positions)
np.concatenate((init_pos, later_positions), axis=1, out=None)

later positions
 [[0.38023047 0.42149282]
 [1.95008091 1.18526632]]


array([[0.29411138, 0.02089936, 0.38023047, 0.42149282],
       [0.99442135, 0.79080608, 1.95008091, 1.18526632]])

No boundary condition yet

In [10]:
number_of_steps = 3
new_pos = init_pos
next_step_positions = init_pos
for i in range(number_of_steps):
    next_step_positions += np.random.uniform(low=0, high=1.0, size=(2, 2))
    np.concatenate((new_pos, next_step_positions, ), axis=1, out=None)
    new_pos =  np.concatenate((init_pos, next_step_positions, ), axis=1, out=None)

print(new_pos)
    

[[5.40075283 4.86173502 5.40075283 4.86173502]
 [6.56083621 8.27568526 6.56083621 8.27568526]]
