In [29]:
import skeleton as s
import numpy as np

1st column: x_coordinate, 
second column: y_coordinate;
size(number of particles, number of dimensions)

In [30]:
init_pos = np.random.uniform(low=0, high=1.0, size=(2, 2))
init_vel = np.random.uniform(low=-430, high=430, size=(2, 2))

print("pos\n", init_pos,"\n vel\n" ,init_vel)
print("y_values\n", init_pos[:, 1])

pos
 [[0.07403622 0.33386521]
 [0.59605291 0.08792389]] 
 vel
 [[ 397.92137222 -140.4495737 ]
 [ 310.62947342  400.83476337]]
y_values
 [0.33386521 0.08792389]


In [31]:
def function(init_pos, init_vel):
    later_positions = np.random.uniform(low=0, high=1.0, size=(2, 2))
    np.concatenate((init_pos, later_positions), axis=1, out=None)
    
function(init_pos, init_vel)

In [32]:
later_positions = init_pos + np.random.uniform(low=0, high=1.0, size=(2, 2))
print("later positions\n" , later_positions)
np.concatenate((init_pos, later_positions), axis=1, out=None)

later positions
 [[1.01341257 1.10865393]
 [1.54628127 0.35430139]]


array([[0.07403622, 0.33386521, 1.01341257, 1.10865393],
       [0.59605291, 0.08792389, 1.54628127, 0.35430139]])

No boundary condition yet

In [36]:
number_of_steps = 3
final_matrix = init_pos
next_step_positions = init_pos

for i in range(number_of_steps):
    next_step_positions += np.random.uniform(low=0, high=1.0, size=(2, 2))
    final_matrix =  np.concatenate((final_matrix, next_step_positions), axis=1, out=None)

print(final_matrix)

[[4.24984241 4.00539917 4.24984241 4.00539917 4.74777679 4.94385783
  5.39256181 5.49919828]
 [5.63565208 5.71525954 5.63565208 5.71525954 6.09226032 6.21216382
  7.07673874 6.70330701]]
