In [43]:
import skeleton as s
import numpy as np

1st column: x_coordinate, 
second column: y_coordinate;
size(number of particles, number of dimensions)

In [44]:
init_pos = np.random.uniform(low=0, high=1.0, size=(2, 2))
init_vel = np.random.uniform(low=-430, high=430, size=(2, 2))

print("pos\n", init_pos,"\n vel\n" ,init_vel)
print("y_values\n", init_pos[:, 1])

pos
 [[0.16749409 0.3064822 ]
 [0.33699676 0.36204361]] 
 vel
 [[-257.25544735  -67.79107335]
 [-275.43922891   71.56325634]]
y_values
 [0.3064822  0.36204361]


In [45]:
def function(init_pos, init_vel):
    later_positions = np.random.uniform(low=0, high=1.0, size=(2, 2))
    np.concatenate((init_pos, later_positions), axis=1, out=None)
    
function(init_pos, init_vel)

In [46]:
later_positions = init_pos + np.random.uniform(low=0, high=1.0, size=(2, 2))
print("later positions\n" , later_positions)
np.concatenate((init_pos, later_positions), axis=1, out=None)

later positions
 [[0.66335538 1.07206957]
 [0.55157311 0.95712928]]


array([[0.16749409, 0.3064822 , 0.66335538, 1.07206957],
       [0.33699676, 0.36204361, 0.55157311, 0.95712928]])

No boundary condition yet

In [47]:
number_of_steps = 3
final_matrix = np.copy(init_pos)
next_step_positions = np.copy(init_pos)

for i in range(number_of_steps):
    next_step_positions += np.random.uniform(low=0, high=1.0, size=(2, 2))
    final_matrix =  np.concatenate((final_matrix, next_step_positions), axis=1, out=None)

print(final_matrix)

[[0.16749409 0.3064822  0.32273961 1.08254179 1.28320997 1.7350674
  1.89406229 2.19461339]
 [0.33699676 0.36204361 1.1324881  0.42002685 1.73802951 0.75464608
  2.2867907  1.32155097]]
