In [ ]:
import skeleton as s
import numpy as np

1st column: x_coordinate, 
second column: y_coordinate;
size(number of particles, number of dimensions)

In [47]:
init_pos = np.random.uniform(low=0, high=1.0, size=(2, 2))
init_vel = np.random.uniform(low=-430, high=430, size=(2, 2))

print("pos\n", init_pos,"\n vel\n" ,init_vel)
print("y_values\n", init_pos[:, 1])

pos
 [[0.33712212 0.25308681]
 [0.13747493 0.94744491]] 
 vel
 [[-273.25571972  368.36829179]
 [ 299.65362447 -272.72019925]]
y_values
 [0.25308681 0.94744491]


In [62]:
def function(init_pos, init_vel):
    later_positions = np.random.uniform(low=0, high=1.0, size=(2, 2))
    np.concatenate((init_pos, later_positions), axis=1, out=None)
    
function(init_pos, init_vel)

In [61]:
later_positions = np.random.uniform(low=0, high=1.0, size=(2, 2))
print("later positions\n" , later_positions)
np.concatenate((init_pos, later_positions), axis=1, out=None)

later positions
 [[0.49112217 0.86110722]
 [0.17178813 0.04853016]]


array([[0.33712212, 0.25308681, 0.49112217, 0.86110722],
       [0.13747493, 0.94744491, 0.17178813, 0.04853016]])

No boundary condition yet