In [57]:
import skeleton as s
import numpy as np

In [66]:
init_pos = np.random.uniform(low=0, high=1.0, size=(2, 2))
init_vel = np.random.uniform(low=-430, high=430, size=(2, 2))
time_step = pow(10, -8)
m = 6.6335 * pow(10, -26) #mass of argon atom
n = 2 #number of particles

In [67]:
print("initial pos\n", init_pos,"\n initial vel\n" ,init_vel)

initial pos
 [[0.77490016 0.53815941]
 [0.76317406 0.85891628]] 
 initial vel
 [[ 183.06998305 -182.99914515]
 [ 132.97494378   30.69172426]]


In [68]:
#compute the forces on the particles at each timestep
def lj_force(position, n):
    e = 1.65*pow(10,-21)
    s = 3.405*pow(10,-10)
    F = 0
    pos = position[:,-n:]
    for j in range(n):
        f = 0    # force on the j-th particle
        for i in range(n-1):
            if i+j+1 >= n: #take into account particles 0,1,....,j-1
                rel_pos=pos[:,j+i+1-n]-pos[:,j] #gives position of i-th particle with resprect to j-th particle (points from i to j)
                r = np.linalg.norm(pos[:,j+i+1-n]-pos[:,j])
                f += rel_pos*((24*e/pow(r,2))*(pow(s/r,6))*((pow(s/r,6))-1))  # ff on the j-th part. from the interaction with the i-th part.
            else: #take into account particles j+1,....,n-1
                rel_pos=pos[:,j+i+1]-pos[:,j] #gives position of i-th particle with resprect to j-th particle (points from i to j)
                r = np.linalg.norm(pos[:,j+i+1]-pos[:,j])
                f += rel_pos*((24*e/pow(r,2))*(pow(s/r,6))*((pow(s/r,6))-1))  # f on the j-th part. from the interaction with the i-th part.
        if j == 0:
            F = f
        else:
            F = np.concatenate((F, f), axis=0, out=None)
    
    F_matrix = np.zeros((2,n)) #2 is the number of dimensions, n is the number of particles
    F_matrix[:n] = F[0:n]
    F_matrix[1:] = F[2:]
    return F_matrix

array([[ 8.07868504e-73, -3.26716572e-73],
       [-8.07868504e-73,  3.26716572e-73]])

In [70]:
final_matrix_pos = np.copy(init_pos)
final_matrix_vel = np.copy(init_vel)

def euler(final_matrix_pos, final_matrix_vel):
    
    latest_pos = np.copy(final_matrix_pos[:,-2:])          #the -2 will eventually become -(number of particles)
    latest_vel = np.copy(final_matrix_vel[:,-2:])
    
    new_latest_pos = latest_pos + latest_vel * time_step
    new_latest_vel = latest_vel + 1/m * lj_force(latest_pos, 2)
    return new_latest_pos, new_latest_vel


(array([[0.77490199, 0.53815758],
        [0.76317539, 0.85891659]]),
 array([[ 183.06998305, -182.99914515],
        [ 132.97494378,   30.69172426]]))

In [80]:
#Create a 2x8 matrix to store the velocity of each particle at each step in time.
next_step_velocity = np.copy(init_vel)

#Create a 2x8 matrix to store the position of each particle at each step in time.
number_of_steps = 3
next_step_position = np.copy(init_pos)

for i in range(number_of_steps):
    next_step_position, next_step_velocity = euler(final_matrix_pos, final_matrix_vel)
    for k in range(2): #implement boundary conditions
        for j in range(2):
            next_step_position[k, j] = next_step_position[k, j]%1
    final_matrix_pos =  np.concatenate((final_matrix_pos, next_step_position), axis=1, out=None)
    final_matrix_vel =  np.concatenate((final_matrix_vel, next_step_velocity), axis=1, out=None)

print(final_matrix_pos)
print(final_matrix_vel)

IndentationError: unexpected indent (<ipython-input-80-d10ccf350fe9>, line 12)

In [63]:
#Create a 2x8 matrix to store the velocity of each particle at each step in time.
final_matrix_vel = np.copy(init_vel)
next_step_velocity = np.copy(init_vel)

for i in range(number_of_steps):
    next_step_velocity += np.random.uniform(low=-100, high=100, size=(2, 2))
    final_matrix_vel =  np.concatenate((final_matrix_vel, next_step_velocity), axis=1, out=None)

print(vel_steps)

[[ -89.25168113 -108.97864129  -83.612957   -195.55931867 -115.52555023
  -179.96365112 -212.74754744 -102.93066735]
 [ 342.09602315  183.17696253  309.51915862  205.9646631   287.26027612
   201.34251367  295.50922301  131.32766511]]
